version: '3'
services:
  waf:
    build: 
      context: .
      dockerfile: ./waf/dockerfile
    ports:
      - "9090:80"
    environment:
      - HOST_ML=ml
      - HOST_WEB=web

  #ml:
  #  image: openresty/openresty:1.21.4.1-0-jammy
  #  volumes:
  #    - ./ml/conf.d:/etc/nginx/conf.d
  #    - ./ml/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  #    - ./ml/logs:/var/log/nginx/
  #    - ./lualib/http.lua:/usr/local/openresty/lualib/resty/http.lua:ro
  #    - ./lualib/http_connect.lua:/usr/local/openresty/lualib/resty/http_connect.lua:ro
  #    - ./lualib/http_headers.lua:/usr/local/openresty/lualib/resty/http_headers.lua:ro
  #  ports:
  #    - 9091:80

  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    ports:
      - "9093:9093"
    volumes:
      - ./dashboard/env:/usr/src/app/dashboard/env
      - ./dashboard/templates:/usr/src/app/dashboard/templates
      - ./dashboard/app.py:/usr/src/app/dashboard/app.py
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=!pyree2023
      - DB_DATABASE=logs
    depends_on:
      - mysql

  web:
    container_name: django
    build: 
      context: .
      dockerfile: ./djangoweb/Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    volumes: 
      - ./djangoweb/env:/usr/src/app/djangoweb/env
      - ./djangoweb/puddle:/usr/src/app/djangoweb/puddle
      - ./djangoweb/.vscode:/usr/src/app/djangoweb/.vscode
    ports:
      - "9092:80"

  mysql:
    build: 
      context: .
      dockerfile: ./dockerfile
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10