version: '3'
services:
    waf:
        build:
            context: .
            dockerfile: ./waf/dockerfile
        volumes:
            - ./waf/conf.d/:/etc/nginx/conf.d/
            - ./waf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./waf/logs/:/var/log/nginx/
            - ./waf/request_blocked.html:/usr/local/openresty/nginx/html/request_blocked.html:ro
        ports:
            - '9090:80'
        env_file:
            - waf.env
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        environment:
            - REQUEST_PATH=${REQUEST_PATH}
            # - REQUEST_PATH=/endpoints/Custom-sklearn-model-2023-12-04-11-50-30/invocations
            - HOST_WEB=web  
        depends_on:
          mysql:
            condition: service_healthy
            
    dashboard:
        build:
            context: .
            dockerfile: ./dashboard/Dockerfile
        env_file:
            - dash.env
        ports:
            - '9093:9093'
        volumes:
            - ./dashboard/env:/usr/src/app/dashboard/env
            - ./dashboard/templates:/usr/src/app/dashboard/templates
            - ./dashboard/app.py:/usr/src/app/dashboard/app.py
        depends_on:
          mysql:
            condition: service_healthy


    web:
        container_name: django
        build:
            context: .
            dockerfile: ./djangoweb/Dockerfile
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
        volumes:
            - ./djangoweb/env:/usr/src/app/djangoweb/env
            - ./djangoweb/puddle:/usr/src/app/djangoweb/puddle
            - ./djangoweb/.vscode:/usr/src/app/djangoweb/.vscode
        ports:
            - '9092:80'
        environment:
            - HOST_WEB=web

    mysql:
        build:
            context: .
            dockerfile: ./dockerfile
        env_file:
            - db.env
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 2s
            retries: 10