FROM openresty/openresty:1.21.4.1-0-jammy
COPY lualib/insert.lua /usr/local/openresty/lualib/resty/insert.lua

FROM mysql:latest
COPY security_logs.sql /docker-entrypoint-initdb.d/security_logs.sql

FROM python:3.11.3

WORKDIR /usr/src/app/djangoweb

COPY ${PWD}/djangoweb/puddle/requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY djangoweb .

WORKDIR /usr/src/app/djangoweb/puddle

EXPOSE 80

CMD ["bash", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:80"]